Graficar_senales_base
EnvolventeJose
Espectrograma_1_STFT_Presion_Labios
Espectrograma_2_Eliminacion_Resonancias_Inferiores_a_300ms
Espectrograma_3_Generacion_curva_a_partir_resonancias
Espectrograma_4_Calculo_flujo_a_partir_curva_presion_labios